In [1]:
### A lot of GPT was used :) 
import torch
import numpy as np 
import sys
from pympler import asizeof

In [2]:
tensor = torch.tensor([1,2,3])
array = np.array([1,2,3])

In [3]:
# Tensors operation 
print(torch.is_tensor(tensor))
print(torch.is_tensor(array))

True
False


In [4]:
# Torch stoarge 
storage = torch.FloatStorage(3)
storage[0] = 10 
storage

/var/folders/fq/gncz_bp52yq728fprlh8k3l40000gn/T/ipykernel_24944/1446601639.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = torch.FloatStorage(3)


 10.0
 0.0
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [5]:
print(torch.is_storage(storage))
print(torch.is_storage(tensor))

True
False


In [6]:
print(f"Size of tensor is {asizeof.asizeof(tensor)} bytes")
print(f"Size of numpy array is {asizeof.asizeof(array)} bytes")
print(f"Size of torch stoarge is {asizeof.asizeof(storage)} bytes")


Size of tensor is 184 bytes
Size of numpy array is 152 bytes
Size of torch stoarge is 576 bytes


In [7]:
# torch also have complex values

real_part = torch.tensor([1.0, 2.0, 3.0])
imag_part = torch.tensor([4.0, 5.0, 6.0])
complex_tensor = torch.complex(real_part, imag_part)

# Check if the tensor is complex
is_complex = torch.is_complex(complex_tensor)
print("Tensor:", complex_tensor)
print("Is complex:", is_complex)

Tensor: tensor([1.+4.j, 2.+5.j, 3.+6.j])
Is complex: True


In [8]:
# Create a complex-valued tensor
real_part = torch.tensor([1.0, 2.0, 3.0])
imag_part = torch.tensor([4.0, 5.0, 6.0])
complex_tensor = torch.complex(real_part, imag_part)

# Conjugate the complex tensor
conjugated_tensor = torch.conj(complex_tensor)

# Check if the conjugated tensor is complex
is_complex = torch.is_complex(conjugated_tensor)

print("Original Tensor:", complex_tensor)
print("Conjugated Tensor:", conjugated_tensor)
print("Is conjugated tensor complex:", is_complex)

Original Tensor: tensor([1.+4.j, 2.+5.j, 3.+6.j])
Conjugated Tensor: tensor([1.-4.j, 2.-5.j, 3.-6.j])
Is conjugated tensor complex: True


In [9]:
# Create a floating-point tensor
float_tensor = torch.tensor([1.0, 2.0, 3.0])

# Check if the tensor is a floating-point tensor
is_floating_point = torch.is_floating_point(float_tensor)

print("Tensor:", float_tensor)
print("Is floating-point:", is_floating_point)

Tensor: tensor([1., 2., 3.])
Is floating-point: True


In [10]:
# Create a tensor
tensor = torch.tensor([0])

# Check if the tensor is non-zero, must be single element 
is_nonzero = tensor.is_nonzero()

print("Tensor:", tensor)
print("Is non-zero:", is_nonzero)

Tensor: tensor([0])
Is non-zero: False


In [11]:
## Change the default tensor creation at once!
# Check the current default data type
print(f"Default dtype: {torch.get_default_dtype()}")
tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"Tensor type after change: {tensor.dtype}")

# Set the default data type to float64 (double precision)
torch.set_default_dtype(torch.float64)

# Check the new default data type
print(f"New default dtype: {torch.get_default_dtype()}")

# Create a tensor to see the effect of the change
tensor = torch.tensor([1.0, 2.0, 3.0])
print(f"Tensor type after change: {tensor.dtype}")

Default dtype: torch.float32
Tensor type after change: torch.float32
New default dtype: torch.float64
Tensor type after change: torch.float64


In [12]:
# Create a tensor of shape (2, 3, 4)
tensor = torch.randn(2, 3, 4)

# Get the total number of elements in the tensor
num_elements = torch.numel(tensor)

print(tensor)
print(f"Tensor shape: {tensor.shape}")
print(f"Total number of elements: {num_elements}")

tensor([[[-0.7619,  0.6812, -0.1475, -1.9871],
         [ 0.8222, -0.9775,  0.3801, -1.0066],
         [-1.2627,  0.6199,  2.5119,  1.1960]],

        [[-0.3847,  1.1081,  2.2749, -2.2328],
         [-1.5795, -0.2692, -0.0962,  0.8014],
         [-0.4453,  2.0358,  0.7457,  0.2346]]])
Tensor shape: torch.Size([2, 3, 4])
Total number of elements: 24


In [14]:
# Print the tensor to see the effect of the print options
print(tensor)

# Create a larger tensor to see the effect of threshold
large_tensor = torch.randn(10, 10)
print(large_tensor)

# Set print options for tensors
# sci_mode: Controls whether tensors are displayed in scientific notation
torch.set_printoptions(precision=3, threshold=6, edgeitems=2, sci_mode=False) # over the threshold print both edge items 

# Create a tensor
tensor = torch.randn(3, 3)

# Print the tensor to see the effect of the print options
print(tensor)

# Create a larger tensor to see the effect of threshold
large_tensor = torch.randn(10, 10)
print(large_tensor)

tensor([[-1.115, -0.527, -2.227],
        [-0.055, -0.466, -1.321],
        [ 0.433,  0.246,  0.454]])
tensor([[ 0.462,  2.611,  ..., -1.138, -0.335],
        [ 0.808,  0.709,  ..., -1.049,  0.296],
        ...,
        [-0.348,  0.142,  ..., -0.716,  1.263],
        [ 0.176, -0.196,  ...,  0.304, -0.766]])
tensor([[ 0.890,  0.160, -0.134],
        [ 1.088, -1.168, -0.382],
        [-0.791, -2.115, -0.768]])
tensor([[-0.652,  0.545,  ...,  0.371, -1.396],
        [ 0.197, -0.182,  ...,  1.163,  1.364],
        ...,
        [-1.382, -0.403,  ..., -1.074,  0.656],
        [ 1.366,  1.455,  ...,  0.445,  0.155]])


In [18]:
# Tensors
## Creates tensor with no autograd history
tensor = torch.tensor([1,2,3])
tensor.requires_grad

False

In [23]:
# Define the dense and sparse tensors
dense_tensor = torch.tensor([[[1, 0, 0], 
                              [0, 2, 0]],
                             
                             [[0, 0, 3], 
                              [0, 0, 0]]])

# Sparse tensor
indices = torch.tensor([[0, 0, 1], [0, 1, 0], [0, 1, 2]])
values = torch.tensor([1, 2, 3])
shape = (2, 2, 3)
sparse_tensor = torch.sparse_coo_tensor(indices, values, shape)

# Check memory size of both tensors
dense_size = asizeof.asizeof(dense_tensor)
sparse_size = asizeof.asizeof(sparse_tensor)

## ??? Dunno
print(f"Memory size of dense tensor: {dense_size} bytes")
print(f"Memory size of sparse tensor: {sparse_size} bytes")


Memory size of dense tensor: 184 bytes
Memory size of sparse tensor: 184 bytes


In [ ]:
from scipy.sparse import csr_matrix, csc_matrix

# 여튼 sparse tensor를 표현하는 방법이 당양하다
# Define the dense matrix
dense_matrix = np.array([
    [0, 0, 3, 0],
    [4, 0, 0, 5],
    [0, 0, 0, 0],
    [6, 7, 0, 0]
])

# Convert to CSR format
csr = csr_matrix(dense_matrix)

# Convert to CSC format
csc = csc_matrix(dense_matrix)

# Print CSR and CSC representations
print("CSR Representation:")
print(csr)
print("CSR in Dense Format:")
print(csr.toarray())  # Convert back to dense

print("\nCSC Representation:")
print(csc)
print("CSC in Dense Format:")
print(csc.toarray())  # Convert back to dense

CSR Representation:
  (0, 2)	3
  (1, 0)	4
  (1, 3)	5
  (3, 0)	6
  (3, 1)	7
CSR in Dense Format:
[[0 0 3 0]
 [4 0 0 5]
 [0 0 0 0]
 [6 7 0 0]]

CSC Representation:
  (1, 0)	4
  (3, 0)	6
  (3, 1)	7
  (0, 2)	3
  (1, 3)	5
CSC in Dense Format:
[[0 0 3 0]
 [4 0 0 5]
 [0 0 0 0]
 [6 7 0 0]]


In [27]:
from scipy.sparse import bsr_matrix
# Define the dense matrix
dense_matrix = np.array([
    [0, 0, 0, 0],
    [0, 0, 2, 0],
    [0, 2, 0, 0],
    [0, 0, 0, 0]
])

# Convert to BSR format (Block size 2x2)
bsr = bsr_matrix(dense_matrix, blocksize=(2, 2))

# Print BSR and BSC representations
print("BSR Representation:")
print(bsr)
print("BSR in Dense Format:")
print(bsr.toarray())  # Convert back to dense


BSR Representation:
  (0, 2)	0
  (0, 3)	0
  (1, 2)	2
  (1, 3)	0
  (2, 0)	0
  (2, 1)	2
  (3, 0)	0
  (3, 1)	0
BSR in Dense Format:
[[0 0 0 0]
 [0 0 2 0]
 [0 2 0 0]
 [0 0 0 0]]


In [37]:
print(torch.asarray([1,2,3]))
print(torch.as_tensor([1,2,3]))
print(torch.as_tensor(torch.tensor([1.,2.,3.], requires_grad=True)))
## This cannot carray over grads!
print(torch.asarray(torch.tensor([1.,2.,3.], requires_grad=True)))

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])


In [38]:
# Create a tensor of shape (4, 4)
x = torch.arange(16).reshape(4, 4)

# Define the new shape (2, 2) and strides
new_shape = (2, 2)
strides = (2 * x.stride(0), 2 * x.stride(1))

# Create a new tensor using torch.as_strided
y = torch.as_strided(x, size=new_shape, stride=strides)

# Print the original tensor and the transformed tensor
print("Original Tensor (4x4):")
print(x)
print("\nTransformed Tensor (2x2):")
print(y)

Original Tensor (4x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

Transformed Tensor (2x2):
tensor([[ 0,  2],
        [ 8, 10]])


In [40]:
# Create a tensor
tensor = torch.randn(3, 3)

# Save the tensor to a file
torch.save(tensor, 'tensor.pt')

# Load the tensor from the file
loaded_tensor = torch.load('tensor.pt')

# Print the loaded tensor
print(loaded_tensor)

import os 
os.remove('tensor.pt')


tensor([[ 0.217,  0.973,  1.538],
        [-0.454, -0.998, -0.448],
        [-0.777,  0.436, -1.779]])


In [41]:
torch.from_numpy(np.array([1,2,3]))

tensor([1, 2, 3])

In [44]:
# Create a Python object that supports the buffer protocol (e.g., bytearray)
buffer_data = bytearray([1, 2, 3, 4, 5, 6])

# Create a memoryview object that exposes the buffer protocol
buffer_view = memoryview(buffer_data)

# Convert the memoryview to a PyTorch tensor
tensor = torch.frombuffer(buffer_view, dtype=torch.uint8)

# Print the tensor
print(tensor)

tensor([1, 2, 3, 4, 5, 6], dtype=torch.uint8)


In [51]:
print(torch.zeros((1,2,3)))
torch.zeros_like(torch.tensor([1,2,3]))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


tensor([0, 0, 0])

In [53]:
print(torch.ones((1,2,3)))
torch.ones_like(torch.tensor([1,2,3]))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])


tensor([1, 1, 1])

In [65]:
print(f"arange(1, 100, 3): {torch.arange(1, 100, 3)}")
print(f"range(1, 100, 3) (deprecated in latest PyTorch versions): {torch.range(1, 100, 3)}")
print(f"linspace(1, 100, 3): {torch.linspace(1, 100, 3)}")
print(f"logspace(1, 10, 3): {torch.logspace(1, 10, 3)}")

arange(1, 100, 3): tensor([ 1,  4,  ..., 94, 97])
range(1, 100, 3) (deprecated in latest PyTorch versions): tensor([  1.,   4.,  ...,  97., 100.])
linspace(1, 100, 3): tensor([  1.000,  50.500, 100.000])
logspace(1, 10, 3): tensor([   10.000, 316227.766, 10000000000.000])


/var/folders/fq/gncz_bp52yq728fprlh8k3l40000gn/T/ipykernel_24944/1352935485.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(f"range(1, 100, 3) (deprecated in latest PyTorch versions): {torch.range(1, 100, 3)}")


In [66]:
torch.eye(10)

tensor([[1., 0.,  ..., 0., 0.],
        [0., 1.,  ..., 0., 0.],
        ...,
        [0., 0.,  ..., 1., 0.],
        [0., 0.,  ..., 0., 1.]])

In [68]:
torch.empty(10)

tensor([0., 0.,  ..., 0., 0.])

In [69]:
# Creates a tensor with uninitialized values
tensor_empty = torch.empty(3, 3)

# Creates a tensor with all values initialized to 0
tensor_zeros = torch.zeros(3, 3)

full = torch.full_like(tensor_empty)

print(tensor_empty)
print(tensor_zeros)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
